### PR TITLE
Update PHP requirements and move CI to Github Actions

### PR DESCRIPTION
**Pull request by jdecool**
As discussed in #18, I've make this PR to update PHP requirements and remove obsolete PHP versions.

I've also update PHPUnit versions and move CI to Github Actions.

### CODE REVIEW

**Comment by jdecool** [comment]
You can see the result of Github Actions here => https://github.com/jdecool/json-stream/actions/runs/480064720

**Review by skolodyazhnyy — APPROVED** [review]

**Comment by jdecool** [comment]
Have you planned to tag a new version soon ?

**Comment by skolodyazhnyy** [comment]
I'm happy to do it, are there any changes pending?

**Comment by skolodyazhnyy** [comment]
I believe it's just options parameter you've added yesterday.

**Comment by jdecool** [comment]
Yes, it's just options parameter.

This PR is a "bonus" because I've notice that some dependencies are old and the CI isn't work.

**Comment by skolodyazhnyy** [comment]
Sure, should be released under 0.4.2 tag.

**Comment by jdecool** [comment]
Great ! Thanks !

The tag exists but it was not released on Packagist.

Last year, Github has changed the webhooks settings.
Maybe you need to update the repository configuration to allow packagist to be notify by webhooks.

**Comment by skolodyazhnyy** [comment]
It should be available here https://packagist.org/packages/bcncommerce/json-stream#0.4.2

**Comment by jdecool** [comment]
I got it.

Thanks again :)

**Pull request merged**
